eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
    metadataMap:
      instanceId: ${vcap.application.instance_id:${spring.application.name}:${server.port:8080}}
  client:    # <--- ADD THE CLIENT SECTION!!!
    serviceUrl:
      defaultZone: ${vcap.services.springbox-service-registry-mn.credentials.uri:http://127.0.0.1:8761}/eureka/